### ISSUE TITLE
Document if it's possible to work with a database

### ISSUE THREAD

**Issue by B-Galati** [jolicode/asynit#33]
Hello and thank you for this great repo :-)

Is it possible to work with a database out of the box? Or it would require some tricks like transactional tests?

**Comment by lyrixx** [comment]
Hello.

It's the same workflow as with PHPUnit (or other test system !)

---

In a project I'm working on:

1. we load fixtures
2. we run rests

But we write tests in order to be able to re-run them without having to clean the database. So basically we have 2 types of fixtures:

1. immutable fixtures, in order (for exemple) to tests permission (401 / 403), and to tests read access
2. mutable fixtures, in order to test write access 

---

Note: I'm totally against transnational test. It's boring to debug !

**Comment by B-Galati** [comment]
Thank you @lyrixx

How can you be sure the tests are really isolated for mutable fixtures?

**Comment by lyrixx** [comment]
It's not ! 

So basically, I use `@Depend('test_a')`, like that I'm sure they are

**Comment by B-Galati** [comment]
Alright thank you!

As working with database/fixtures is something quite common in functional tests. Do you think it would be worth mentioning these details in the README?

Another question unrelated. Does it make sense to use this lib if one does not make real HTTP call? Like using symfony/browser-kit. I don't think so but perhaps I am missing something.

**Comment by lyrixx** [comment]
> As working with database/fixtures is something quite common in functional tests. Do you think it would be worth mentioning these details in the README?

I don't know. If you want to submit a PR, we will be glad to merge it ;)

> Another question unrelated. Does it make sense to use this lib if one does not make real HTTP call? Like using symfony/browser-kit. I don't think so but perhaps I am missing something.

No, IMHO it does not make sens. Instead you should rely on amphp, the lib that powers asynit

**Comment by lyrixx** [comment]
Could we close this issue?

**Comment by B-Galati** [comment]
Yeap, thanks a lot for your insights :+1:
